### ISSUE TITLE
NullReferenceException when loading project with Advance Menu docked

### ISSUE THREAD

**Issue by KingRecycle** [daemon3000/InputManager#10]
If you dock the Adv. Input window and relaunch the project it will create an error.

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorStyles.get_label () (at C:/buildslave/unity/build/Editor/Mono/GUI/EditorStyles.cs:11)

Can be prevented by not docking.

Unfortunate as I would like to dock this.

**Comment by daemon3000** [comment]
The issue has been fixed. You can now dock the advanced editor window.

**Comment by seifeHu** [comment]
I write a unity tool and  meet the same problem too, Can you point out  how to fix? 
thanks!

**Comment by daemon3000** [comment]
In my case there was an issue with creating new GUIStyle objects in OnEnable when the window was docked.

To fix the issue I moved the GUIStyle creation to a new method where I check if any GUIStyle is null and if it's null I create it. This method is then called at the start of the OnGUI method.
