### ISSUE TITLE
Advanced Editor Refocus field glitch

### ISSUE THREAD

**Issue by petersvp** [daemon3000/InputManager#12]
Unity 5: Advanced editor: When refocusing a control in the left tree, on the right, the text field still shows old key's text instead of the new key.

E.g. create new default config, click Horizontal from  the left, select and renale it to "Strafe", then select the Vertical one and notice the glitch.

**Comment by daemon3000** [comment]
Fixed it by setting the focused GUI control to null when the selection changes.
