### ISSUE TITLE
Using InputManager with Standalone Input Module

### ISSUE THREAD

**Issue by Jestus** [daemon3000/InputManager#18]
So I am using the new Unity 4.6.x UI, which I believe added the EventSystem and Standalone Input Module to the scene automatically.

I've created my Input Manager and overridden Unity's standard Input Manager with this custom one. However, I get errors originating from my Standalone Input Module that my axes "Horizontal" and "Vertical" "are not setup" even though I have defined them in the Input Editor.

It appears that by disabling the Standalone Input Module my UI Clicks cease to work and buttons do not function. Do you know of a way to make Unity's SIM work with this InputManager/recognize my axes, or is there another workaround?

**Comment by daemon3000** [comment]
https://github.com/daemon3000/InputManager/wiki/Standalone%20Input%20Module
