### ISSUE TITLE
OnLevelWasLoaded was found on PauseManager

### ISSUE THREAD

**Issue by magyar123** [daemon3000/InputManager#21]
Hi!
The plugin is very cool, and works find but it keeps logging this warning message in the console:

> OnLevelWasLoaded was found on PauseManager
> This message has been deprecated and will be removed in a later version of Unity.
> Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed

**Comment by magyar123** [comment]
Oh and also this warning:

> Assets/InputManager/Addons/InputAdapter/Runtime/InputAdapter.cs(616,46): warning CS0618: `UnityEngine.RuntimePlatform.OSXWebPlayer' is obsolete: `WebPlayer export is no longer supported in Unity 5.4+.'

**Comment by daemon3000** [comment]
I haven't updated the project to Unity 5.4 yet so that's why you probably get the warnings. I'll update it tomorrow or next week but it's nothing you should worry about.

**Comment by magyar123** [comment]
Thanks!

**Comment by daemon3000** [comment]
What Unity version are you using? Is it a beta version? I imported the plugin in Unity 5.4 and didn't get any warnings.

**Comment by magyar123** [comment]
My version of Unity is 5.4.1f1.
BTW, I renamed the method `OnLevelWasLoaded` to `_OnLevelWasLoaded`, and added this to start: `SceneManager.sceneLoaded += _OnLevelWasLoaded` and it works fine.

**Comment by daemon3000** [comment]
Nevermind, it was just me being stupid. I had the warnings set to hidden in the console.

**Comment by daemon3000** [comment]
Fixed the warnings.
