### ISSUE TITLE
InputManager export fail

### ISSUE THREAD

**Issue by reberzon** [daemon3000/InputManager#25]
Attempting to export an InputManager.asset file that uses input characters "[" and "]" fails.

If these are replaced with other characters, the issue is resolved.
Enclosed are sample .asset files that demonstrate the issue.
Stack crawl from failure also enclosed.

[InputManagerAssetFail.zip](https://github.com/daemon3000/InputManager/files/976829/InputManagerAssetFail.zip)

**Comment by daemon3000** [comment]
@reberzon Fixed it.
