### ISSUE TITLE
XmlException

### ISSUE THREAD

**Issue by zisaboy** [daemon3000/InputManager#27]
hi! i use GoogleAnalytics and report this issue. but, i can not be reproduced.

XmlException: expected '>' (3E) but found 'EOF' (FFFFFFFF) Line 127, position 14. Mono.Xml2.XmlTextReader.Expect (Int32 expected) Mono.Xml2.XmlTextReader.ReadStartTag () Mono.Xml2.XmlTextReader.ReadContent () Mono.Xml2.XmlTextReader.Read () System.Xml.XmlTextReader.Read () TeamUtility.IO.InputLoaderXML.ReadAxisConfiguration (System.Xml.XmlReader reader) TeamUtility.IO.InputLoaderXML.ReadInputConfiguration (System.Xml.XmlReader reader) TeamUtility.IO.InputLoaderXML.Load () TeamUtility.IO.InputManager.Load (IInputLoader inputLoader)  GoogleAnalyticsV4:HandleException(String, String, LogType) UnityEngine.Application:CallLogCallback(String, String, LogType, Boolean)

thanks!
i want to load this xml file.
[sample.txt](https://github.com/daemon3000/InputManager/files/1067420/sample.txt)

**Comment by daemon3000** [comment]
Can you attach the file you are trying to load?

**Comment by daemon3000** [comment]
I fixed the loading issue with the file you attached. It was related to the file encoding. Did you make changes to the [InputSaverXML.cs](https://github.com/daemon3000/InputManager/blob/master/Assets/InputManager/Source/Runtime/_Support/InputSaverXML.cs) file? How did you create the sample file?  Let me know if you still have issues with it.

**Comment by zisaboy** [comment]
HI! I did not change the InputSaverXML.cs file. And, I use your sample code to create the sample file.

StringBuilder output = new StringBuilder();
InputSaverXML saver = new InputSaverXML(output);
InputManager.Save(saver);

Thank you for your help. Wish you a good day.
