### ISSUE TITLE
Yaml exception when trying to export Unity settings

### ISSUE THREAD

**Issue by Ikillnukes** [daemon3000/InputManager#28]
This happens when you try to backup your old settings from Unity at the first times.

SyntaxErrorException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 2, Idx: 1): While scanning for the next token, find character that cannot start any token.
UnityInputConverter.YamlDotNet.Core.Scanner.FetchNextToken ()
UnityInputConverter.YamlDotNet.Core.Scanner.FetchMoreTokens ()
UnityInputConverter.YamlDotNet.Core.Scanner.MoveNextWithoutConsuming ()
UnityInputConverter.YamlDotNet.Core.Parser.GetCurrentToken ()
UnityInputConverter.YamlDotNet.Core.Parser.ParseDocumentStart (Boolean isImplicit)
UnityInputConverter.YamlDotNet.Core.Parser.StateMachine ()
UnityInputConverter.YamlDotNet.Core.Parser.MoveNext ()
UnityInputConverter.YamlDotNet.Core.ParserExtensions.Allow[StreamStart] (IParser parser)
UnityInputConverter.YamlDotNet.Serialization.Deserializer.Deserialize (IParser parser, System.Type type)
UnityInputConverter.YamlDotNet.Serialization.Deserializer.Deserialize (System.IO.TextReader input, System.Type type)
UnityInputConverter.YamlDotNet.Serialization.Deserializer.Deserialize[IDictionary`2] (System.IO.TextReader input)
UnityInputConverter.InputConverter.ConvertUnityInputManager (System.String sourceFile, System.String destinationFile)
TeamUtilityEditor.IO.InputManager.EditorToolbox.OverwriteInputSettings () (at Assets/InputManager/Source/Editor/_Support/EditorToolbox.cs:173)
UnityEngine.Debug:LogException(Exception)
TeamUtilityEditor.IO.InputManager.EditorToolbox:OverwriteInputSettings() (at Assets/InputManager/Source/Editor/_Support/EditorToolbox.cs:177)
TeamUtilityEditor.IO.InputManager.EditorToolbox:ShowStartupWarning() (at Assets/InputManager/Source/Editor/_Support/EditorToolbox.cs:119)
TeamUtilityEditor.IO.AdvancedInputEditor:OnEnable() (at Assets/InputManager/Source/Editor/AdvancedInputEditor.cs:108)
UnityEditor.EditorWindow:GetWindow(String)
TeamUtilityEditor.IO.AdvancedInputEditor:OpenWindow() (at Assets/InputManager/Source/Editor/AdvancedInputEditor.cs:1041)

I tried in a new project and the same happened.

**Comment by daemon3000** [comment]
@Ikillnukes Please attach the "InputManager.asset" file you're trying to backup, from the "ProjectSettings" folder.

**Comment by Ikillnukes** [comment]
Sorry, I make a mistake, I will move this to UnityInputManager.
