### ISSUE TITLE
DelayedIntField is better than IntField

### ISSUE THREAD

**Issue by Ikillnukes** [daemon3000/InputManager#29]
I've been squeezing my mind because I has some problem editing Axis from InputManager, because, they were deleted when I edited their sizes. I wasn't testing some bools, but searching in the Unity ScriptReference I see this:

https://docs.unity3d.com/ScriptReference/EditorGUILayout.DelayedIntField.html

@daemon3000 I suggest you to use them. The main problem here, is that if you are editing them, and you want to edit the value from 12 to 13, when you erase the 2 to write a 3, you resize it to 1, when you write 13, you have 12 values copied from the first value.

I had make some changes to your InputManagerEditor.cs. I forked and edit it, thanks!

Pull request: https://github.com/daemon3000/InputManager/pull/30

**PD:** Maybe there are a lot of changes, but this is caused because of Visual Studio.

**Comment by daemon3000** [comment]
@Ikillnukes I merged your pull request.
