### ISSUE TITLE
Reloading scripts during play mode corrupts InputManager and InputAdapter internal state

### ISSUE THREAD

**Issue by petersvp** [daemon3000/InputManager#32]
This issue can be tough, since usually not everybody writes his game 100% himself.
Currently, InputManager cannot survive script reload during play mode which makes it impossible for use during PlayMode and concurrent code tweaking.
I workarounded the issue by using the inputManager only during runtime and plain old Input.Get calls during editor.

All my other scripts and custom scripts survive reload successfully.
In order to survive a Assembly Reload during Play Mode without corrupting the entire projects of users, you should overall, only use serialized attributes.

If you indeed need to use private nonserialized, then handle the ReInitialization in OnEnable! If you properly reinit, user's playmode tweaking in  code will not be interrupted.

**Comment by petersvp** [comment]
WORKAROUND:  InputManager.cs:92  - Replace Awake with OnEnable allows assemblies reinit and looks like reinits properly for me - I managed to reload ~10 times with no issues [one being breaking change from my side that had to restart the game]

**Comment by daemon3000** [comment]
@petersvp Please make a pull request if you have a fix. I'm busy at the moment so I won't be to work on it for at least another week.

**Comment by petersvp** [comment]
I don't know what consequences may be if I rename Awake to OnEnable. Also, I am not even using git on my project so I won't do pull request without knowing it is stable :) I just found an issue and quick workaround, hopefully helping others (and that usecase... usually nobody cares about play mode reloads)

**Comment by daemon3000** [comment]
@petersvp Added "experimental" support for script reloading for InputManager, InputAdapter, InputEventManager. Let me know if you run into any issues.

**Comment by petersvp** [comment]
Very nice, after a quick test in my AssetTest Play mode, reloading scripts survived fully. Considewring issue as fixed and also, I never heard about the DidReloadScripts callback, so thanks.
