### ISSUE TITLE
Same axis name for 2 different inputmethods impossible?

### ISSUE THREAD

**Issue by mads256c** [daemon3000/InputManager#33]
Is there a way to do this in this InputManager. It is possible to do in Unity's builtin inputmanager.
This is what i want to do:
http://i.imgur.com/Vd1pJQN.jpg
http://i.imgur.com/8epqB8D.jpg

I want to change weapon when i scroll with the scroll wheel and when i press Q or E. With the axis value indicating if it should go to the next or previous weapon.

Sorry for bad or hard to understand English

**Comment by daemon3000** [comment]
@mads256c No, it's not possible. Axis names must be different.
