### ISSUE TITLE
"Unable to parse YAML file" when opening project

### ISSUE THREAD

**Issue by Celtc** [daemon3000/InputManager#34]
After adding the InputManager every time I open any project an error is displayed in console several times:

```
Unable to parse YAML file: [mapping values are not allowed in this context] at line 1
Unable to parse YAML file: [mapping values are not allowed in this context] at line 1
Unable to parse YAML file: [mapping values are not allowed in this context] at line 1
Unable to parse YAML file: [mapping values are not allowed in this context] at line 1
```

I tried creating a new project, erasing the appdata's folder, even uninstalling / installing Unity. But the problem is still there.

**Comment by daemon3000** [comment]
@Celtc What Unity version? I haven't updated in a while.

**Comment by Celtc** [comment]
I installed the InputManager on a project using Unity 2017.1.1. But after the error appeared, even opening projects in Unity 5.6.2 displays the error.

**Comment by daemon3000** [comment]
@Celtc OK, I'll look at it tomorrow. They probably made changes to the YAML serializer in Unity 2017 and when you overwrite the input settings it corrupts your project settings. Delete the plugin and restore your old "ProjectSettings/InputManager.asset" file if you can. If you don't use version control just create a new 2017 project and copy over the file from there.

**Comment by Celtc** [comment]
The problem is that if I create a new project, a blank project, the error is there. It seems that some share file between projects has been modified, not just the project where I installed the InputManager.

**Comment by Celtc** [comment]
Removing the plugin from all the projects seems to have fixed it. Strange thing that Unity shows errors related to the plugin in projects where it wasn't installed.

I'm closing this issue. Although, as you said, it's proabably an issue related to the new Unity 2017 and will still occur in this new version.

Thanks for your quicks replies. And sorry for my bad english.

**Comment by daemon3000** [comment]
@Celtc Can you reproduce this error? I imported the plugin as a unitypackage file(exported from Unity 5.6) in a new Unity 2017 project and it all worked fine.

**Comment by Celtc** [comment]
I'm attaching just the plugin folder and the project settings folder. Open it as a standalone project and the error will appear.
[YAMLError.zip](https://github.com/daemon3000/InputManager/files/1303555/YAMLError.zip)

**Comment by daemon3000** [comment]
@Celtc It's not my plugin. You had a merge conflict that changed the [ProjectVersion.txt](https://pastebin.com/jKP2Vz3y) file to something that can't be parsed by the YAML serializer and throws those errors. You have the commit ID on the last line so you can track down when/where the error happened.

Change the contents of the the file to this and it should work:
`m_EditorVersion: 2017.1.0p4`

Download and open [YAMLError_Fixed.zip](https://goo.gl/ksqrSA) to confirm that it fixes the issue.
