### ISSUE TITLE
Special buttons like Control does not work 

### ISSUE THREAD

**Issue by theodor349** [daemon3000/InputManager#41]
From what I understand you should be able to bind a key like "space", by typing in the normal Unity keycode for "space". 
This I currently can't get working with LeftControl, LeftShift and so on. As well as Keypad0,1,2...

**Comment by daemon3000** [comment]
You have to use "left ctrl", "left shift", etc. It's the same names you'd normally use in "Edit/Project Settings/Input". I made a new [Wiki page](https://github.com/daemon3000/InputManager/wiki/Key-Names) with all the key names.

**Comment by theodor349** [comment]
Okay.
Thanks a lot .
