### ISSUE TITLE
Floats may be parsed and written with different cultures

### ISSUE THREAD

**Issue by idbrii** [daemon3000/InputManager#45]
Floats like deadzone [are parsed with InvariantCulture](https://github.com/daemon3000/InputManager/blob/master/Assets/InputManager/Source/Runtime/InputLoaderXML.cs#L400) but [written with default culture](https://github.com/daemon3000/InputManager/blob/master/Assets/InputManager/Source/Runtime/InputSaverXML.cs#L156).

On saving, users on French-language systems will write "0,5" instead of "0.5" (invalid in InvariantCulture) and results in a FormatException from ReadAttributeAsFloat on loading.

I believe using `ToString(CultureInfo.InvariantCulture)` for each of the floats passed to `WriteElementString` would resolve the issue.

**Comment by daemon3000** [comment]
Should be fixed now. Let me know if it's still an issue.
