### ISSUE TITLE
InputManager.IsScanning is execution order dependent

### ISSUE THREAD

**Issue by Exerionius** [daemon3000/InputManager#49]
Example code:
```C#
if(!InputManager.IsScanning) {
    if(InputManager.GetButtonDown("Cancel")) {
        // do stuff for cancel only if it is not scan cancel
    }
}
```
Here two possible results of this code:
1. If this script is executed first, this code will correctly detect the fact that InputManager is scanning right now and we should not do anything.
2. If the InputManager code is executed first, this code will fail to detect the fact of input scanning, because the InputManager cleared the `IsScanning` flag already, but `GetButtonDown("Cancel")` still returns true for this frame.

In general we have no idea in what order the scripts execute, and this behavior is not deterministic. I use the same button for a scan cancel and a back menu navigation, and I use the same code in two places: a title screen menu and a in-game menu. In the title screen scene it works like an example №1, while in-game it works like an example №2.
We can set the execution order manually in the Unity settings, but it's not a very good practice.

**Comment by daemon3000** [comment]
The InputManager script should execute before everything else. This is by design. Put the InputManager script at the top of the execution order in the project settings. It should have been there already if you exported a unity package from the plugin project. Not sure what happened.

**Comment by Exerionius** [comment]
But... if the Input Manager executes first, it will clear out the IsScanning flag before other scripts can read it, and the code above will not work.

In that case, how to detect if cancel button was pressed to cancel scan and not anything else?

**Comment by daemon3000** [comment]
I'm not sure what the issue is. Is this a case where you try to cancel a scan but since navigation is on the same button it will both stop the scan and exit the menu when you press the button(because it all executes on the same frame and the button is still pressed)?

**Comment by daemon3000** [comment]
One(hacky) way to do it is to have a private boolean that locks the navigation(instead of checking InputManager.IsScanning) and restore navigation with a one frame delay using a coroutine(so the Cancel button is no longer pressed).

	private bool isNavigationLocked = false;

	//	Lock navigation before you start the scan
	LockNavigation();
	InputManager.StartScan(settings, OnScanComplete);

	private bool OnScanComplete(ScanResult result)
	{
		//	Do stuff here.
		//	And unlock navigation.
		StartCoroutine(UnlockNavigation());	
		return true;
	}

	private void LockNavigation()
	{
		isNavigationLocked = true;
	}

	private IEnumerator UnlockNavigation()
	{
		// Wait one frame so the Cancel button is not pressed anymore.
		yield return null;
		isNavigationLocked = false;
	}

I can't think of any proper solution for this. I would have to alter the state of the button from the scan function and I can't do that because under the hood it's just a call to **Input.GetKeyDown** and I can't force a key to not be down(unless I manage my own keyboard state and that would require major changes).

**Comment by Exerionius** [comment]
Yes, I was using a similar workaround with 1-frame-delay-coroutine, but instead of a custom flag I was setting `EventsSystem.current.sendNavigationEvents` to true and false accordingly. Strangely it works for 'up' and 'down' navigation events when I need to scan 'Vertical' input (being the same button as a menu vertical navigation), but for some reason it doesn't work for a Escape button in a different scene.
I will investigate further as I get home. I was hoping for a better solution, but if it is as it is, I need to find a problem in my code.

**Comment by Exerionius** [comment]
Yep, it's confirmed: setting `EventsSystem.current.sendNavigationEvents` to false will prevent an automatic UI navigation, but will not prevent other scripts from reading button presses (obviously).

So in the end, I had to implement a custom flag in the UI manager to check for scanning. I was hoping that the InputManager.isScanning flag can be a little bit more useful for that case, but if it is by design, so be it.

**Comment by daemon3000** [comment]
So I realized I can just move the input scan in LateUpdate that way your navigation code will always run before **IsScanning** becomes false and on the next frame the button won't be pressed anymore. Get the plugin from the **dev** branch and see if it works without any frame delay workarounds.

**Comment by Exerionius** [comment]
Just checked and it works like a charm. I'm a bit conserned about backward compatibility though. In my case I'm just starting out and it's fine, but I can not estimate a potential impact on existing projects.
Thanks!

**Comment by daemon3000** [comment]
As far as backwards compatibility is concerned I can just add a toggle or something in the inspector and let you toggle between Update and LateUpdate so it won't be an issue.

**Comment by daemon3000** [comment]
Added Update/LateUpdate option in the inspector. It's available on the master branch now.
