### ISSUE TITLE
Editor Resources should be under the editor folder

### ISSUE THREAD

**Issue by idbrii** [daemon3000/InputManager#50]
There are two Resource folders:

InputManager/Assets/InputManager/Source/Resources
InputManager/Assets/InputManager/Addons/UIInputModule/Resources

They're [only accessed from editor code](https://github.com/daemon3000/InputManager/search?q=resources.load&unscoped_q=resources.load), so they should be under Editor so that they aren't loaded in standalone games:

InputManager/Assets/InputManager/Source/Editor/Resources
InputManager/Assets/InputManager/Addons/UIInputModule/Editor/Resources

Otherwise, each user needs to strip them out themselves to reduce the cost of their resource bundle.

**Comment by daemon3000** [comment]
Done
