### ISSUE TITLE
Gamepad on control schemes for Gamepad 2 & 3 turn into Gamepad 1 upon loading input configuration

### ISSUE THREAD

**Issue by SpeedFrame** [daemon3000/InputManager#58]
I'm having an issue with customizable input... I don't even have it for controllers, only keyboard and mouse, but when loading the configuration the control schemes for Controllers 2 & 3 change their gamepad value to controller 1. I've checked in the actual XML file, and nothing seems to be wrong there:
![thefile](https://user-images.githubusercontent.com/35924486/81501874-e45c4700-92da-11ea-840a-fe12c530987b.png)

Yet when I check in the input editor after loading the configuration (InputManager.Load), this is how it looks:
![afterload](https://user-images.githubusercontent.com/35924486/81501885-f9d17100-92da-11ea-8663-6b0d911cdaf7.png)

This is how it's supposed to look:
![beforeload](https://user-images.githubusercontent.com/35924486/81501905-15d51280-92db-11ea-981c-ac40747eaf17.png)

If you can't find a fix for this, can you at least tell me how to only load the KeyboardAndMouse scheme? Because it's only the controller configurations that become bugged. Thanks :D

**Comment by daemon3000** [comment]
Can you send me the XML file you're trying to load?

**Comment by SpeedFrame** [comment]
Sure, here's the file! If it matters, I use my own "file format" but had to rename it to TXT for github to accept it.

[controls.txt](https://github.com/daemon3000/InputManager/files/4611209/controls.txt)

**Comment by daemon3000** [comment]
The issue should be fixed now. It was a bug in the XML file loader.
