### ISSUE TITLE
Convert a joystick axis(the trigger) to a button(Fire1) 

### ISSUE THREAD

**Issue by Elit3d** [daemon3000/InputManager#6]
Currently there is no way to do this. Would be really cool to bind axis to button. Lets say Fire1 was RightTrigger and I wanted to bind it to A, this currently cant be done

**Comment by daemon3000** [comment]
This  is now supported through a new input type named _AnalogButton_. The [RebindInput](https://github.com/daemon3000/InputManager/blob/master/Assets/InputManager/Examples/01%20-%20Controls%20Menu/Scripts/RebindInput.cs) script that comes with the controls menu example shows how to use it. To test it run the controls menu example, go to **Controls > Edit Gamepad** and try to bind an axis to the _Jump_ button.
