### ISSUE TITLE
ResetInput separate for joystick and keyboard

### ISSUE THREAD

**Issue by Elit3d** [daemon3000/InputManager#7]
Currently there isnt a way to Reset input for the different UI buttons (keyboard and joystick) this feature would be great

**Comment by daemon3000** [comment]
If what you're referring to is resetting input configurations(keyboard or joystick for example) to a default state it can already be done and is shown in the controls menu example(see the [ResetInputConfiguration](https://github.com/daemon3000/InputManager/blob/master/Assets/InputManager/Examples/01%20-%20Controls%20Menu/Scripts/ResetInputConfiguration.cs) script).

**Comment by Elit3d** [comment]
say if i had a keyboard button Fire1 and a joystick button Fire1 on same canvas, I can reset them seperate?
