### ISSUE TITLE
Rebinding Example broken.

### ISSUE THREAD

**Issue by ChrisClark13** [daemon3000/InputManager#8]
I downloaded the library and went to the rebinding example because that's what I'm planning on using in my game.

To my surprise when I clicked on the buttons for rebinding one of the inputs... nothing seemed to happen.
I dove into the source code to find the error and poked around a fair bit. Eventually I found myself in the InputManager.Update() function where I found that when it was supposed to scan for input it just went straight to calling StopInputScan() which passes along KeyCode.None to _scanHandler.

That results in the scan result instantly cancelling on itself and that functionality being completely broken. It seems this bug was introduced in https://github.com/daemon3000/InputManager/commit/d6c332622966646c8f4fc474d594f3048301d6dd .

I changed StopInputScan() to ScanInput() and then the example worked just as expected, though I have a feeling that this isn't the correct fix for this problem. Perhaps reverting that small section to what was changed in that commit would fix it?

**Comment by daemon3000** [comment]
The issue has been fixed.
